# This example uses YAML anchors which allows reuse of multiple keys
# without having to repeat yourself.
# Also see https://github.com/Mic92/dotfiles/blob/d6114726d859df36ccaa32891c4963ae5717ef7f/nixos/.sops.yaml
# for a more complex example.
keys:
  - &apfel ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIIpOQirGxMfUl3F8KQxjzDZg0POSIpeNk5ayZQvugQOm li.aldric@gmail.com
  - &nix-wsl ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIHg3soSwDR48yhLBm6KvBQliWcNbaPgd1D3QEk+Nu8EN li.aldric@gmail.com#nix-wsl
  - &debian ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPlXUXQeII1CLwhf83/Y8fMLQ0qAai7MrthZrhElsRhF li.aldric@gmail.com#debian
creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - age:
          - *apfel
          - *nix-wsl
          - *debian
