[mgr]
sort_by        = "natural"
sort_sensitive = true
sort_reverse   = false
sort_dir_first = true
linemode       = "none"
show_hidden    = false
show_symlink   = true

[preview]
tab_size        = 2
max_width       = 600
max_height      = 900
cache_dir       = ""
image_filter    = "triangle"
image_quality   = 80
ueberzug_offset = [0, 0, 0, 0]
ueberzug_scale  = 1

[opener]
edit = [{ run = 'nvim "$@"', block = true }]

[plugin]
prepend_previewers = [{ mime = "audio/*", run = "exifaudio" }]
prepend_fetchers = [
	{ id = "git", name = "*", run = "git" },
	{ id = "git", name = "*/", run = "git" },
]
