sshconfig: ENC[AES256_GCM,data:B38elLpyM9o0ul/RRET/tvzEhQ2MMAQWy6Dj9XhalSL1IDHSfNIqsePgTU7WttCOC51WZCjcPTr/f/JtAx37Gcjmx4y48WUv516QiwQ524GNuAv11N9H+hsJ8uhcFNpDb8ryrhF6+XhDiMDridhkJJj0RVa/GZx+4MdTqd4refHSORg55fTyIlP/VeZiO+G52qVBh4d3YzPyplJC+CAiinlBELbDtx153p7TMgpKCsS+rTHYPN2084Qka6qWNxjBBhbwphGeJTA3L/F2vtNBYtzZ2eHfaJyWzPFbl5/dyc88+guvZGfhb3eQ8CSgzHxe7Ib6Gn935iREMD6NnOX9ua0460Vq0OdsSx8gnCOYBd/g270JJJmRG/QlnRp3Uw42iMNNcvjQoMqlO92hvsSDy/hhxragKSpHZkvuGgyN5dn5hmjq7Tyzom/8mufEuUFjMYQv8zPHaxQ2AnnpKjXV1L2iaOjljIwFR/UtwKjJQAl1f10S0uNUn0Oe4EWaoglERU9X3pO/rPGisdOvyzkHnzJM4gi8GRvUN0jHogcP1hvIIVu9WZ0=,iv:QbgDU45nyaU6IH4UIJS91ZH2HvYQMHY2U1H9di55lrU=,tag:9UWi+FVjx1DuqqPiKoEEtg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpU3lYS3M5a0tDNXVFQ080
            ajNMNVhQYkovdk1NTDJQZlJwQURUWHRNOEM0CmVNUjY2dFJ0eEhnZ3FKY3RPVG16
            eHBuR2tBcGZWMGtCRVlZLy9zOU84ZzgKLS0tIEdVZHVkL21GSFg3QU50Y3JuaHpp
            RHJUMC9WUnFZb09YcnZhbmQ1OHNFVkUKcmjyzOeLu9E2hSSTKPDhRR2W4NKDFO02
            k0hYkEVMsAjVhHzvSLjDJkiBom6VurGxR+OZyGoJRnYCYmi4SjlfCw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1uyg73jl64msxu5x7rmed0japawg22z7qqdye5xj9a7tx2vaqpdnqe3jdmx
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArNldyYStybDRnK0VxZ0tE
            enZuYk9naTV6UFR5NHNGcEZiZjR2SWJPS0g4Ck8rVHFEWEVXcjgxdGN3WWZQQmNq
            OUg5OFNkVy9CV1BKQmZzQlpVWW5ZQlUKLS0tIHArc21mYjgvVVBnRVd4NWFJS1JH
            MlZOeDNxdGVxWkFsZ3J2WFJCdWNLQ1UKHZG688CCA9mB50ifJgieaFEL8mPXhQW/
            O4aYxkYW6qXLp/eYmNdwXEpbKRlzAWWEYoXIEN7cagLZ/UzI54LsPg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1y8n4p9de897fepp6cxk0jtz7jynkmexgyhgyjtwmsvkuu09mk56qfyzsr7
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsRC93ZVkweitHeFNSL2hO
            UzhvZ2hQaEcycFQvcTFEMktwcno3K0owZXlRCkN3cyt4MjVVSlYyMXRycFpDdTRh
            TzYwYzZjQVA5eWJva1lTb0JuNzBvSkEKLS0tIEZVczlmNkZITWU0dUdKT2tmdkxC
            Uy9MQ21yYVBacTAvMXVlbm5BMTNUNE0Kl9G+XFr6tsqIVZmlpDHsXK0zGaqsnTou
            WyLJj4zoMCKLmc9aJLKdVg9INJCuoIPPWoPsjwSnc7SedUzJBxBaUA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1955ta5htsxpmpwa2j64gznev5hh4tnz8v5asnz6q2mjlxjkzt4hs6sgyyf
    lastmodified: "2026-09-22T19:00:23Z"
    mac: ENC[AES256_GCM,data:5URtZQOAcxglpvOx51ZLhpLpW3Q0Qxv87JjCzTwkb5J8fvbdE2+/F9yblQyGwRsfl9uTQIXmjUAne2B+eeXGOBL/93ReMkGlp2um1ZIMPYMxVV5uCB0FkW8bq9HZDhL8XzIGc6TGyNXp3mg8n33YMehW1okfzHr+FlK0Tmyj/Kw=,iv:l21/GzOvCKX+L3v10gN7g3FxbpmlkkTWL3qxYovmvOM=,tag:+8znfFiunpwquVsFm8ZA5Q==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
