sshconfig: ENC[AES256_GCM,data:M+t8mlqoolVtonWYAzOfeQdtM/sY7VItCsAsbG9tKYSMiTWzU93/PMZ20xNmwKern+MEaBw5JIr3aXfzabW1l6skP1Z417lg3RxJ1edTO+sfqczrebwTQhvqe2iCnA9g+wg/GgD1iNz4bJg8ZJ1kOSt7NelLm3GyfAZxMBj697NS/VTDng0SAo8O2YOL5pjzmewZdVnffTndPCRuNcwWsYDSs+Ul8H6ovfPurZvuk9clHwFp8fKEn9yUxQnLaW9/tstzLHohavfhcVDBB6HPeLQbWcRfHNeAUke1f+BOcg/iexenaMqfeKqf7uHnjtVgimgug1OepJiUduGUXS1IeYOZX/2heQQT1r45OlBzBrJGTINpmOgxWqW0iyVhHEuevQWqMAJYVa7Zlj5WGsGG5JR/6dtH1POf1idhpOjxZWmTU0Gu5CoY6l0Ih6bnxFRIamaQK9E38RfS3R+sywGr2ydT5jIywcFuztZhh9nbKyX1b3iAKhO8Xg==,iv:4NW+riYYCxxR6I6jXKJO0HybFlwppb5ZLYZlEwiPmuc=,tag:JQqPahZbnljXVY2mgk8DZA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpU3lYS3M5a0tDNXVFQ080
            ajNMNVhQYkovdk1NTDJQZlJwQURUWHRNOEM0CmVNUjY2dFJ0eEhnZ3FKY3RPVG16
            eHBuR2tBcGZWMGtCRVlZLy9zOU84ZzgKLS0tIEdVZHVkL21GSFg3QU50Y3JuaHpp
            RHJUMC9WUnFZb09YcnZhbmQ1OHNFVkUKcmjyzOeLu9E2hSSTKPDhRR2W4NKDFO02
            k0hYkEVMsAjVhHzvSLjDJkiBom6VurGxR+OZyGoJRnYCYmi4SjlfCw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1uyg73jl64msxu5x7rmed0japawg22z7qqdye5xj9a7tx2vaqpdnqe3jdmx
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArNldyYStybDRnK0VxZ0tE
            enZuYk9naTV6UFR5NHNGcEZiZjR2SWJPS0g4Ck8rVHFEWEVXcjgxdGN3WWZQQmNq
            OUg5OFNkVy9CV1BKQmZzQlpVWW5ZQlUKLS0tIHArc21mYjgvVVBnRVd4NWFJS1JH
            MlZOeDNxdGVxWkFsZ3J2WFJCdWNLQ1UKHZG688CCA9mB50ifJgieaFEL8mPXhQW/
            O4aYxkYW6qXLp/eYmNdwXEpbKRlzAWWEYoXIEN7cagLZ/UzI54LsPg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1y8n4p9de897fepp6cxk0jtz7jynkmexgyhgyjtwmsvkuu09mk56qfyzsr7
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsRC93ZVkweitHeFNSL2hO
            UzhvZ2hQaEcycFQvcTFEMktwcno3K0owZXlRCkN3cyt4MjVVSlYyMXRycFpDdTRh
            TzYwYzZjQVA5eWJva1lTb0JuNzBvSkEKLS0tIEZVczlmNkZITWU0dUdKT2tmdkxC
            Uy9MQ21yYVBacTAvMXVlbm5BMTNUNE0Kl9G+XFr6tsqIVZmlpDHsXK0zGaqsnTou
            WyLJj4zoMCKLmc9aJLKdVg9INJCuoIPPWoPsjwSnc7SedUzJBxBaUA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1955ta5htsxpmpwa2j64gznev5hh4tnz8v5asnz6q2mjlxjkzt4hs6sgyyf
    lastmodified: "2026-08-30T15:35:53Z"
    mac: ENC[AES256_GCM,data:QTSqqt2jnYOd5AYqBcZri2nQ6cAHwxdnTKixjJuYVsgKf5h36Cm9VXsmM/xhLVNTP2VzPwLjs5LRDB+AFDSWqff3Ipld01TxuP8wdyvuy/HSEPd5GEGfk6Sw27BGiNs+0PbP6XTB/DZtm+oLuncG3v1Mxgn2ia8FNjPthc8vAgg=,iv:e5GtOmiM7BpxlZMHJcLMZCp29x2XUhtK8jeRHLglZUY=,tag:PNYp9Ruam2oCF75SIObhvw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
